### ISSUE TITLE
Ship only the necessary files to the npm registry

### ISSUE THREAD

**Issue by paulrberg** [compound-finance/compound-js#29]
The [@compound-finance/compound-js](https://unpkg.com/browse/@compound-finance/compound-js@0.3.1/) production package includes ALL the files in this repository. This clutters our projects that install your package with unnecessary files.

The solution is to use a [files](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files) field in `package.json` - this would act as an allowlist for the files that are supposed to be shipped to the npm registry.

**Comment by ajb413** [comment]
Hi @paulrberg. Thank you for bringing this up. I will look into this. If you beat me to it, please feel free to open a pull request with improvements.

**Comment by ajb413** [comment]
merged in #30 and published as 0.3.2
