### ISSUE TITLE
Suggestion to mark as "ethers.js" as peer dependency

### ISSUE THREAD

**Issue by paulrberg** [compound-finance/compound-js#31]
It is not an error to list a package as both a normal dependency and a peer dependency. In fact, in certain cases it is the recommended approach. More on that [here](https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/).

Compound.Js relies heavily on Ethers - if, say, a user has installed v4 of Ethers but then installs Compound.Js, things might break. It's better to explicitly ask the user to import v5.

**Comment by ajb413** [comment]
@paulrberg Hey take a look at #32. Does that look right to you? I think the only other effect of the change is that users of npm <7 will need to do `npm i @compound-finance/compound-js ethers@5` instead of only `npm i @compound-finance/compound-js`.

**Comment by paulrberg** [comment]
Yup, #32 looks good.

> users of npm <7 will need to do `npm i @compound-finance/compound-js ethers@5` instead of only `npm i @compound-finance/compound-js`

True, but they would have been in trouble had they not used ethers v5. Better safe than sorry.

**Comment by ajb413** [comment]
Added in 0.4.0.
