### ISSUE TITLE
Rinkeby Account API throws error

### ISSUE THREAD

**Issue by thegitparticle** [compound-finance/compound-js#36]
When using Rinkeby testnet, the Compound.api.account call throws this error

`{"error": "Compound [api] [account] | [object Object]", "responseCode": undefined, "responseMessage": undefined}`

It works fine with 'ropsten' as given in the example.

**Comment by ajb413** [comment]
Hello, the Compound testnet APIs are now deprecated.

**Comment by thegitparticle** [comment]
how do I test transactions, information query of borrow positions and all?
