### ISSUE TITLE
TSLint errors and deprecation

### ISSUE THREAD

**Issue by leonrinkel** [compound-finance/compound-js#4]
TSLint has been deprecated and should be migrated to ESLint. Also there are like 1000 linting errors. Fixing these errors would require removing types like `any` and `object` and replacing them with proper types (e.g. API request/response types). It would improve readability, IntelliSense, type safety and make the code less vulnerable to common mistakes. If this is not already in the works, I'd like to work this and propose a PR on this issue by the weekend.

Reference: [https://github.com/palantir/tslint/issues/4534](https://github.com/palantir/tslint/issues/4534).

**Comment by ajb413** [comment]
Great idea! I will take a look myself sometime this week.

**Comment by ajb413** [comment]
Added in 0.2.0 👍
