### ISSUE TITLE
Problems using the lib in web mode through NPM

### ISSUE THREAD

**Issue by nicosampler** [compound-finance/compound-js#5]
I had a hard time trying to use the lib with React installing from npm.

It was impossible to import it like so: `import Compound from '@compound-finance/compound-js'`, it was returning always an empty object. I found a way to import it like  so:  `import Compound from @compound-finance/compound-js/dist/nodejs/src`.

After that the instantiation was not working with  `new Compound(...)`, I had to do `const comp = Compound()`, neither the access to the prototype attributes like `Compound.cUSDT`.

**Comment by ajb413** [comment]
This looks like a bug. It should work with `import Compound from '@compound-finance/compound-js'`. I am investigating now.

**Comment by ajb413** [comment]
Thank you for calling this out @nicosampler ! Fixed in `0.1.5`. The issue was a line in `package.json`. Removing the `browser` key-value in favor of `main` fixed the issue. You can now do:

```js
import Compound from '@compound-finance/compound-js';
```

**Comment by nicosampler** [comment]
Thx, one no relaed question, do you know why the api is returning 500 on rinkeby? Where should I report it? Already did on Discord
