### ISSUE TITLE
PriceFeed: incorrect price data

### ISSUE THREAD

**Issue by riordant** [compound-finance/compound-js#50]
`const pf = Compound.util.getAddress(Compound.PriceFeed)` returns contract 
`0x65c816077C29b557BEE980ae3cC2dCE80204A0C5`

when using the `price` function here to get price data for COMP, it's returning 
`57570000`

which in an incorrect price, and appears to be static.

**Comment by ajb413** [comment]
The price feed address is now `0x50ce56A3239671Ab62f185704Caedf626352741e`. I will make a PR later today and push a new version of the SDK. Thank you for pointing this out.

**Comment by ajb413** [comment]
Fixed in v0.5.2
